social_auth_mastodon.settings:
  type: config_object
  label: 'Social Auth Mastodon settings'
  mapping:
    instance:
      type: string
      label: 'Mastodon Instance'
    client_id:
      type: string
      label: 'Client ID'
    client_secret:
      type: string
      label: 'Client Secret'
