social_auth_mastodon.settings:
  type: config_object
  label: 'Social Auth Mastodon settings'
  mapping:
    instance:
      type: string
      label: 'The Mastodon instance'
    client_id:
      type: string
      label: 'Client ID'
    client_secret:
      type: string
      label: 'Client Secret'
    scopes:
      type: string
      label: 'Scopes to be requested'
    endpoints:
      type: string
      label: 'API Endpoints to be requested'
